name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'python-3.8.6-linux-20.04-x64.tar.gz'  # Adjust to the required Python version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dh-make devscripts build-essential python3-setuptools python3-wheel alien rpm

    - name: Build source distribution
      run: python3 setup.py sdist

    - name: Create Debian package
      run: |
        PACKAGE_NAME=$(python3 setup.py --name)
        PACKAGE_VERSION=$(python3 setup.py --version)
        dh_make -s -y -f dist/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz
        dpkg-buildpackage -us -uc

    - name: Convert Debian to RPM
      run: |
        PACKAGE_NAME=$(python3 setup.py --name)
        PACKAGE_VERSION=$(python3 setup.py --version)
        sudo alien --to-rpm ../${PACKAGE_NAME}_${PACKAGE_VERSION}-1_all.deb
        mkdir -p artifacts/rpm
        mv *.rpm artifacts/rpm/

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v2
      with:
        name: rpm-packages
        path: artifacts/rpm/*.rpm

